-- MySQL Script generated by MySQL Workbench
-- mar. 28 mars 2017 14:54:51 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Parcours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parcours` (
  `idParcours` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idParcours`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Etudiant` (
  `idEtudiant` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Prénom` VARCHAR(45) NULL,
  `Parcours_idParcours` INT NOT NULL,
  INDEX `fk_Etudiant_Parcours1_idx` (`Parcours_idParcours` ASC),
  PRIMARY KEY (`idEtudiant`),
  CONSTRAINT `fk_Etudiant_Parcours1`
    FOREIGN KEY (`Parcours_idParcours`)
    REFERENCES `mydb`.`Parcours` (`idParcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cours` (
  `idCours` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idCours`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Possède`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Possède` (
  `Parcours_idParcours` INT NOT NULL,
  `Cours_idCours` INT NOT NULL,
  PRIMARY KEY (`Parcours_idParcours`, `Cours_idCours`),
  INDEX `fk_Parcours_has_Cours_Cours1_idx` (`Cours_idCours` ASC),
  INDEX `fk_Parcours_has_Cours_Parcours1_idx` (`Parcours_idParcours` ASC),
  CONSTRAINT `fk_Parcours_has_Cours_Parcours1`
    FOREIGN KEY (`Parcours_idParcours`)
    REFERENCES `mydb`.`Parcours` (`idParcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parcours_has_Cours_Cours1`
    FOREIGN KEY (`Cours_idCours`)
    REFERENCES `mydb`.`Cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
